name: ci

on: ['push', 'pull_request']

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: ⭐ ESLint ⭐
        run: npm run eslint

      - name: ⭐ Prettier ⭐
        run: npm run prettier

      - name: ⭐ Build ⭐
        run: npm run build
